[package]
name = "fileman"
version = "0.0.1"
description = "Wayland-first NPTK-based file manager for the Nepsod desktop."
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "GPL-3.0"

[dependencies]
npio = { workspace = true }
nptk = { workspace = true }
nptk-fileman-widgets = { workspace = true }
nptk-widgets-extra = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
smol = { workspace = true }
async-trait = { workspace = true }
env_logger = "0.11"
nalgebra = { workspace = true }
trash = "5"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
toml_edit = "0.22"
xdg = "2.5"

[dev-dependencies]
tempfile = "3"
